config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'favourite', to: 'events#favourite'
  root to: 'pages#welcome'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def username
    return self.email.split('@')[0].capitalize
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  #GET /events/favourite
  def favourite
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user = current_user
    respond_to do |format|
      if @event.save
        format.html { redirect_to events_url, notice: 'Esemény sikeresen létrehozva!' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_url, notice: 'Esemény frissítése sikeres!' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Esemény törlése sikeres!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :location, :description, :date, :category, :participants)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table style="border-spacing: 1em; border-collapse: separate;">
    <tr>
      <td><%= form.label 'Név' %></td>
      <td><%= form.text_field :name, id: :event_name %></td>
    </tr>
    <tr>
      <td><%= form.label 'Helyszín' %></td>
      <td><%= form.text_field :location, id: :event_location %></td>
    </tr>
    <tr>
      <td><%= form.label 'Leírás' %></td>
      <td><%= form.text_area :description, id: :event_description, cols: "60", rows: "3" %></td>
    </tr>
    <tr>
      <td><%= form.label 'Dátum' %></td>
      <td><%= form.datetime_select :date, id: :event_date %></td>
    </tr>
    <tr>
      <td> <%= form.label 'Kategória' %></td>
      <td> <%= form.select :category, ['Művészet', 'Sport', 'Szórakozás', 'Egyetem', 'Kiállítás', 'Utazás'] %></td>
    </tr>
    <tr>
      <td><%= form.label 'Résztvevők' %></td>
      <td><%= form.number_field :participants, id: :event_participants, :value => 0 %></td>
    </tr>
  </table>

  <div class="actions">
    <%= form.submit 'Létrehozás' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Esemény szerkesztése</h1>

<%= render 'form', event: @event %>

<%= link_to 'Megtekint', @event %> |
<%= link_to 'Vissza', events_path %>

app/views/events/favourite.html.erb
<h1 align="center">Kedvenc kategória eseményei</h1>
<% @fav_events = Event.where(category: current_user.favourite) %>
<% @fav_events.each do |fae| %>
  <div class="event_div">
    <h3><%= fae.name %>, <%= fae.location %></h3>
    <article>
      <div><%= fae.description %></div>
      <ul class="show_ul">
        <li class="show_li">Kategória: <%= fae.category %></li>
        <li class="show_li">Résztvevők: <%= fae.participants %></li>
        <li class="show_li">Szervező: <%= fae.user.username %></li>
        <li class="show_li_last"><%= button_to 'Feliratkozás', fae, :method => :get %></li>
      </ul>
    </article>
    <footer class="show_footer"><%= fae.date %></footer>
  </div>
<% end %>

<%= link_to 'Vissza', :back %>

app/views/events/index.html.erb
<main>
  <% @events.each do |e| %>
    <div class="event_div">
      <h3><%= e.name %>, <%= e.location %></h3>
      <article>
        <div><%= e.description %></div>
        <ul class="show_ul">
          <li class="show_li">Kategória: <%= e.category %></li>
          <li class="show_li">Résztvevők: <%= e.participants %></li>
          <li class="show_li">Szervező: <%= e.user.username %></li>
          <li class="show_li_last"><%= button_to 'Feliratkozás', e, :method => :get %></li>
        </ul>
      </article>
      <footer class="show_footer"><%= e.date %></footer>
      <% if current_user && current_user.admin %>
        <td><%= link_to 'Szerkesztés', edit_event_path(e) %></td>
        <td><%= button_to 'Törlés', e, :method => :delete, data: { confirm: 'Biztos benne?' } %></td>
      <% end %>
    </div>
  <% end %>
</main>

<br>
<%= link_to 'Vissza', :back %>

app/views/events/new.html.erb
<h1>Új esemény</h1>

<%= render 'form', event: @event %>

<%= link_to 'Vissza', :back %>

app/views/events/show.html.erb
<p>
  <strong>Név:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Helyszín:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Leírás:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Dátum:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Kategória:</strong>
  <%= @event.category %>
</p>

<p>
  <strong>Résztvevők:</strong>
  <% @event.participants += 1 %>
  <% @event.save %>
  <%= @event.participants %>
</p>

<p>
  <strong>Létrehozó:</strong>
  <%= @event.user.username %>
</p>

<%= link_to 'Vissza', events_path %>

app/views/layouts/_alerts.html.erb
<p class=><%= notice %></p>
<p class=><%= alert %></p>

app/views/layouts/_navbar.html.erb
<% if current_user %>
  <ul class="navbar_ul">
    <li class="navbar_li"><a><%= link_to 'Főoldal', root_path %></a></li>
    <li class="navbar_li"><a><%= link_to 'Események', events_path %></a></li>
    <li class="navbar_li"><a><%= link_to 'Új esemény megadása', new_event_path %></a></li>
    <li class="navbar_li"><a><%= link_to 'Kedvenc kategória eseményei', favourite_path %></a></li>
    <li class="navbar_li"><a><%= link_to 'Profil módosítása', edit_user_registration_path %></a></li>
    <li class="navbar_li"><a><%= link_to 'Kijelentkezés', destroy_user_session_path, method: :delete %></a></li>
  </ul>
<% else %>
  <ul class="navbar_ul">
    <li class="navbar_li"><a><%= link_to 'Bejelentkezés', new_user_session_path %></a></li>
    <li class="navbar_li"><a><%= link_to 'Regisztráció', new_user_registration_path %></a></li>
  </ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rendezvényszervező</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'navbar' %>
    <%= stylesheet_link_tag 'eventshow' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="page-wrap">
    <%= render 'layouts/alerts' %>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/welcome.html.erb
<% if current_user %>
  <h1 align="center">Üdvözöljük <%= current_user.username %>!
    <% if current_user.admin %>
      (admin)
    <% end %>
  </h1>
  <p align="center"><strong>Legnépszerűbb események:</strong></p>
  <% popular_events = Event.order(participants: :desc).first(8) %>
  <% popular_events.each do |pe| %>
    <div class="event_div">
      <h3><%= pe.name %>, <%= pe.location %></h3>
      <article>
        <div><%= pe.description %></div>
        <ul class="show_ul">
          <li class="show_li">Kategória: <%= pe.category %></li>
          <li class="show_li">Résztvevők: <%= pe.participants %></li>
          <li class="show_li_last">Szervező: <%= pe.user.username %></li>
        </ul>
      </article>
    </div>
  <% end %>
<% else  %>
  <h1 align="center">Üdvözöljük kedves vendégünket!</h1>
  <% first_events = Event.first(2) %>
  <% first_events.each do |fe| %>
    <div class="event_div">
      <h3><%= fe.name %>, <%= fe.location %></h3>
      <article>
        <div><%= fe.description %></div>
        <ul class="show_ul">
          <li class="show_li_not_signed">Kategória: <%= fe.category %></li>
        </ul>
      </article>
      <footer class="show_footer"><%= fe.date %></footer>
    </div>
  <% end %>
  <p align="center"><strong>További eseményekhez jelentkezzen be vagy regisztráljon!</strong></p>
<% end %>